import type { CellItem, UnassignedMember } from "./types";

export const getCells = (): CellItem[] => [
  {
    id: 1,
    name: "다윗셀",
    department: "청년 2부",
    leader: "박지은",
    memberCount: 6,
    maxMembers: 10,
    submissionRate: 85,
    status: "ACTIVE",
  },
  {
    id: 2,
    name: "에스더셀",
    department: "청년 2부",
    leader: "김하은",
    memberCount: 7,
    maxMembers: 10,
    submissionRate: 72,
    status: "ACTIVE",
  },
  {
    id: 3,
    name: "모세셀",
    department: "청년 2부",
    leader: "이준호",
    memberCount: 6,
    maxMembers: 8,
    submissionRate: 90,
    status: "ACTIVE",
  },
  {
    id: 4,
    name: "요셉셀",
    department: "청년 2부",
    leader: "정민서",
    memberCount: 8,
    maxMembers: 10,
    submissionRate: 60,
    status: "ACTIVE",
  },
  {
    id: 5,
    name: "룻셀",
    department: "청년 2부",
    leader: null,
    memberCount: 0,
    maxMembers: 10,
    submissionRate: null,
    status: "PENDING",
  },
  {
    id: 6,
    name: "사무엘셀",
    department: "청년 2부",
    leader: "강서윤",
    memberCount: 5,
    maxMembers: 8,
    submissionRate: 80,
    status: "ACTIVE",
  },
  {
    id: 7,
    name: "느헤미야셀",
    department: "청년 2부",
    leader: "윤도현",
    memberCount: 7,
    maxMembers: 9,
    submissionRate: 86,
    status: "ACTIVE",
  },
  {
    id: 8,
    name: "여호수아셀",
    department: "청년 2부",
    leader: "조하영",
    memberCount: 6,
    maxMembers: 8,
    submissionRate: 83,
    status: "ACTIVE",
  },
  {
    id: 9,
    name: "다니엘셀",
    department: "청년 2부",
    leader: "임지호",
    memberCount: 5,
    maxMembers: 8,
    submissionRate: 75,
    status: "ACTIVE",
  },
  {
    id: 10,
    name: "이사야셀",
    department: "청년 2부",
    leader: "송예진",
    memberCount: 4,
    maxMembers: 8,
    submissionRate: null,
    status: "ARCHIVED",
  },
];

export const getUnassignedMembers = (): UnassignedMember[] => [
  {
    id: 101,
    name: "김태현",
    role: "LEADER",
    department: "청년 1부",
    phone: "010-1111-2222",
  },
  {
    id: 102,
    name: "최서진",
    role: "LEADER",
    department: "청년 2부",
    phone: "010-1111-3333",
  },
  {
    id: 103,
    name: "윤지후",
    role: "MEMBER",
    department: "청년 1부",
    phone: "010-2222-1111",
  },
  {
    id: 104,
    name: "박나연",
    role: "MEMBER",
    department: "청년 2부",
    phone: "010-2222-3333",
  },
  {
    id: 105,
    name: "이도경",
    role: "MEMBER",
    department: "청년 2부",
    phone: "010-3333-1111",
  },
  {
    id: 106,
    name: "정하민",
    role: "MEMBER",
    department: "대학부",
    phone: "010-3333-2222",
  },
  {
    id: 107,
    name: "송유진",
    role: "MEMBER",
    department: "대학부",
    phone: "010-4444-1111",
  },
  {
    id: 108,
    name: "한예준",
    role: "MEMBER",
    department: "청년 1부",
    phone: "010-4444-2222",
  },
];
