import type { CellDetail, CellItem, UnassignedMember } from "./types";

export const getCells = (): CellItem[] => [
  {
    id: 1,
    name: "다윗셀",
    department: "청년 2부",
    leader: "박지은",
    memberCount: 6,
    maxMembers: 10,
    submissionRate: 85,
    status: "ACTIVE",
  },
  {
    id: 2,
    name: "에스더셀",
    department: "청년 2부",
    leader: "김하은",
    memberCount: 7,
    maxMembers: 10,
    submissionRate: 72,
    status: "ACTIVE",
  },
  {
    id: 3,
    name: "모세셀",
    department: "청년 2부",
    leader: "이준호",
    memberCount: 6,
    maxMembers: 8,
    submissionRate: 90,
    status: "ACTIVE",
  },
  {
    id: 4,
    name: "요셉셀",
    department: "청년 2부",
    leader: "정민서",
    memberCount: 8,
    maxMembers: 10,
    submissionRate: 60,
    status: "ACTIVE",
  },
  {
    id: 5,
    name: "룻셀",
    department: "청년 2부",
    leader: null,
    memberCount: 0,
    maxMembers: 10,
    submissionRate: null,
    status: "PENDING",
  },
  {
    id: 6,
    name: "사무엘셀",
    department: "청년 2부",
    leader: "강서윤",
    memberCount: 5,
    maxMembers: 8,
    submissionRate: 80,
    status: "ACTIVE",
  },
  {
    id: 7,
    name: "느헤미야셀",
    department: "청년 2부",
    leader: "윤도현",
    memberCount: 7,
    maxMembers: 9,
    submissionRate: 86,
    status: "ACTIVE",
  },
  {
    id: 8,
    name: "여호수아셀",
    department: "청년 2부",
    leader: "조하영",
    memberCount: 6,
    maxMembers: 8,
    submissionRate: 83,
    status: "ACTIVE",
  },
  {
    id: 9,
    name: "다니엘셀",
    department: "청년 2부",
    leader: "임지호",
    memberCount: 5,
    maxMembers: 8,
    submissionRate: 75,
    status: "ACTIVE",
  },
  {
    id: 10,
    name: "이사야셀",
    department: "청년 2부",
    leader: "송예진",
    memberCount: 4,
    maxMembers: 8,
    submissionRate: null,
    status: "ARCHIVED",
  },
];

export const getUnassignedMembers = (): UnassignedMember[] => [
  {
    id: 101,
    name: "김태현",
    role: "LEADER",
    department: "청년 1부",
    phone: "010-1111-2222",
  },
  {
    id: 102,
    name: "최서진",
    role: "LEADER",
    department: "청년 2부",
    phone: "010-1111-3333",
  },
  {
    id: 103,
    name: "윤지후",
    role: "MEMBER",
    department: "청년 1부",
    phone: "010-2222-1111",
  },
  {
    id: 104,
    name: "박나연",
    role: "MEMBER",
    department: "청년 2부",
    phone: "010-2222-3333",
  },
  {
    id: 105,
    name: "이도경",
    role: "MEMBER",
    department: "청년 2부",
    phone: "010-3333-1111",
  },
  {
    id: 106,
    name: "정하민",
    role: "MEMBER",
    department: "대학부",
    phone: "010-3333-2222",
  },
  {
    id: 107,
    name: "송유진",
    role: "MEMBER",
    department: "대학부",
    phone: "010-4444-1111",
  },
  {
    id: 108,
    name: "한예준",
    role: "MEMBER",
    department: "청년 1부",
    phone: "010-4444-2222",
  },
];

export const getCellDetail = (cellId: number): CellDetail => {
  const details: Record<number, CellDetail> = {
    1: {
      id: 1,
      name: "다윗셀",
      description: "예배와 말씀, 기도 나눔을 중심으로 운영되는 청년 2부 셀입니다.",
      department: "청년 2부",
      year: 2026,
      status: "ACTIVE",
      maxMembers: 10,
      inviteCode: "DAVID85",
      inviteCodeExpiresAt: "2026-05-15",
      leader: {
        name: "박지은",
        phone: "010-2121-3434",
      },
      stats: {
        averageSubmissionRate: 85,
        totalPrayerRequests: 23,
        activePrayerRequests: 7,
      },
      members: [
        {
          id: 201,
          name: "박지은",
          cellRole: "LEADER",
          phone: "010-2121-3434",
          joinedAt: "2026-01-12",
          recentSubmissionWeek: "4월 4주",
          submissionRate: 96,
        },
        {
          id: 202,
          name: "김현우",
          cellRole: "MEMBER",
          phone: "010-1212-4545",
          joinedAt: "2026-01-18",
          recentSubmissionWeek: "4월 4주",
          submissionRate: 88,
        },
        {
          id: 203,
          name: "이서영",
          cellRole: "MEMBER",
          phone: "010-9876-1111",
          joinedAt: "2026-02-01",
          recentSubmissionWeek: "4월 3주",
          submissionRate: 80,
        },
        {
          id: 204,
          name: "최민재",
          cellRole: "MEMBER",
          phone: "010-7777-2222",
          joinedAt: "2026-02-08",
          recentSubmissionWeek: "4월 4주",
          submissionRate: 74,
        },
        {
          id: 205,
          name: "정다은",
          cellRole: "MEMBER",
          phone: "010-3333-1212",
          joinedAt: "2026-02-15",
          recentSubmissionWeek: "4월 2주",
          submissionRate: 86,
        },
      ],
    },
  };

  return details[cellId] ?? details[1];
};
