import type { CellItem } from "./types";

export const getCells = (): CellItem[] => [
  {
    id: 1,
    name: "다윗셀",
    department: "청년 2부",
    leader: "박지은",
    memberCount: 6,
    maxMembers: 10,
    submissionRate: 85,
    status: "ACTIVE",
  },
  {
    id: 2,
    name: "에스더셀",
    department: "청년 2부",
    leader: "김하은",
    memberCount: 7,
    maxMembers: 10,
    submissionRate: 72,
    status: "ACTIVE",
  },
  {
    id: 3,
    name: "모세셀",
    department: "청년 2부",
    leader: "이준호",
    memberCount: 6,
    maxMembers: 8,
    submissionRate: 90,
    status: "ACTIVE",
  },
  {
    id: 4,
    name: "요셉셀",
    department: "청년 2부",
    leader: "정민서",
    memberCount: 8,
    maxMembers: 10,
    submissionRate: 60,
    status: "ACTIVE",
  },
  {
    id: 5,
    name: "룻셀",
    department: "청년 2부",
    leader: null,
    memberCount: 0,
    maxMembers: 10,
    submissionRate: null,
    status: "PENDING",
  },
  {
    id: 6,
    name: "사무엘셀",
    department: "청년 2부",
    leader: "강서윤",
    memberCount: 5,
    maxMembers: 8,
    submissionRate: 80,
    status: "ACTIVE",
  },
  {
    id: 7,
    name: "느헤미야셀",
    department: "청년 2부",
    leader: "윤도현",
    memberCount: 7,
    maxMembers: 9,
    submissionRate: 86,
    status: "ACTIVE",
  },
  {
    id: 8,
    name: "여호수아셀",
    department: "청년 2부",
    leader: "조하영",
    memberCount: 6,
    maxMembers: 8,
    submissionRate: 83,
    status: "ACTIVE",
  },
  {
    id: 9,
    name: "다니엘셀",
    department: "청년 2부",
    leader: "임지호",
    memberCount: 5,
    maxMembers: 8,
    submissionRate: 75,
    status: "ACTIVE",
  },
  {
    id: 10,
    name: "이사야셀",
    department: "청년 2부",
    leader: "송예진",
    memberCount: 4,
    maxMembers: 8,
    submissionRate: null,
    status: "ARCHIVED",
  },
];
